In [2]:
%run ./linear_algebra.ipynb

In [17]:
A = np.array([
    [5, -4, 1, 0],
    [-4, 6, -4, 1],
    [1, -4, 6, -4],
    [0, 1, -4, 5]
])

B = np.array([-1,2,1,3])


X = solve_gauss_elimination(A, B)

X

array([ 5.8, 10.2, 10.8,  7.2])

In [21]:
L,U,M,P = lu_decompose(A)


In [22]:
M @ B

array([-1.        ,  1.2       ,  2.57142857,  6.        ])

In [24]:
U

array([[ 5.        , -4.        ,  1.        ,  0.        ],
       [ 0.        ,  2.8       , -3.2       ,  1.        ],
       [ 0.        ,  0.        ,  2.14285714, -2.85714286],
       [ 0.        ,  0.        ,  0.        ,  0.83333333]])

In [29]:
A = np.array([
    [1., 0, -7/15, 0],
    [0, 1, ((16*7)/(15*5)), 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

B = np.array([
    [5.,-4.,1,0],
    [0,14./5,-16./5,0],
    [0,0,15/7,0],
    [0,0,0,35./42]
])

print(A@B)

[[ 5.00000000e+00 -4.00000000e+00  1.37456184e-17  0.00000000e+00]
 [ 0.00000000e+00  2.80000000e+00 -1.26459689e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.14285714e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  8.33333333e-01]]
