In [1]:
%run ./linear_algebra.ipynb

In [2]:
def list1_q4a():
    A = np.array([
        [5, -4, 1, 0],
        [-4, 6, -4, 1],
        [1, -4, 6, -4],
        [0, 1, -4, 5]
    ])

    B = np.array([-1,2,1,3])


    jacobi_result = solve_jacobi(A, B)
    gauss_seidel_result = solve_gauss_seidel(A, B)

    print(jacobi_result)
    print(jacobi_result)
    
list1_q4a()

-1
-1


In [12]:
def lis1_q4b():
    A = np.array([
        [5, -4, 1, 0],
        [-4, 6, -4, 1],
        [1, -4, 6, -4],
        [0, 1, -4, 5]
    ])
    
    M4 = np.array([
        [1/5, 0, 0, 0],
        [0, 5/14, 0, 0],
        [0, 0, 7/15, 0],
        [0, 0, 0, 6/5]
    ])
    
    M1 = np.array([
        [1., 0, 0, 0],
        [4/5, 1, 0, 0],
        [-1/5, 0, 1, 0],
        [0, 0, 0, 1]
    ])
    
    M2 = np.array([
        [1., 0, 0, 0],
        [0, 1, 0, 0],
        [0, 8/7, 1, 0],
        [0, -5/14, 0, 1]
    ])
        
    M3 = np.array([
        [1., 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 4/3, 1]
    ])
            
    M1L = np.array([
        [1., 0, 0, 0],
        [0, 1, 0, -1.2],
        [0, 0, 1, 3.429],
        [0, 0, 0, 1]
    ])
                
    M2L = np.array([
        [1., 0, -7/15, 0],
        [0, 1, 112/75, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])
                    
    M3L = np.array([
        [1., 10/7, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])
    
    expected = np.linalg.inv(A)
    result =  M4 @ M3L @ M2L @ M1L @ M3 @ M2 @ M1
    
    print(expected)
    print(result)
    print(determinant(A))

lis1_q4b()

[[1.2 1.6 1.4 0.8]
 [1.6 2.6 2.4 1.4]
 [1.4 2.4 2.6 1.6]
 [0.8 1.4 1.6 1.2]]
[[1.20009524 1.60016667 1.40019048 0.80014286]
 [1.60015238 2.60026667 2.40030476 1.40022857]
 [1.40013333 2.40023333 2.60026667 1.6002    ]
 [0.8        1.4        1.6        1.2       ]]
24.99999999999998


In [11]:
def list1_q6():
    A = np.array([
        [16,9,8,7,6,5,4,3,2,1],
        [9,17,9,8,7,6,5,4,3,2],
        [8,9,18,9,8,7,6,5,4,3],
        [7,8,9,19,9,8,7,6,5,4],
        [6,7,8,9,18,9,8,7,6,5],
        [5,6,7,8,9,17,9,8,7,6],
        [4,5,6,7,8,9,16,9,8,7],
        [3,4,5,6,7,8,9,15,9,8],
        [2,3,4,5,6,7,8,9,14,9],
        [1,2,3,4,5,6,7,8,9,13]
    ])
    
    
    B = np.array([4,0,8,0,2,0,8,0,4,0])
    
    gauss_result = solve_gauss_elimination(A, B)
    gauss_seidel_result = solve_gauss_seidel(A, B)
    
    print("Resultado por Eliminação de Gauss:", np.round(gauss_result, 3))
    print("Resultado por Gauss-Seidel:", np.round(gauss_seidel_result, 3))
    print("Determinante:", determinant(A))
    
list1_q6()

Resultado por Eliminação de Gauss: [ 0.229 -0.358  0.613 -0.274 -0.048 -0.342  0.818 -0.431  0.479 -0.35 ]
Resultado por Gauss-Seidel: [ 0.229 -0.358  0.613 -0.274 -0.048 -0.342  0.818 -0.431  0.479 -0.35 ]
Determinante: 20385044096.0
