In [1]:
import numpy as np

# Inputs

In [2]:
# A = np.matrix(
#     [[5, -4, 1, 0],
#     [-4, 6, -4, 1],
#     [1, -4, 6, -4],
#     [0, 1, -4, 5]]
# )

In [3]:
# A = np.matrix(
#     [[1, 2, 2],
#     [4, 4, 2],
#     [4, 6, -4]]
# )

In [4]:
A = np.matrix(
    [[1, 2, 2],
    [4, 4, 2],
    [4, 6, 4]]
)

In [5]:
B = [ -1, 2, 1, 3]

# Implementation

## Gauss elimination

In [6]:
def get_upper_linear_combination_matrix_step(input_matrix, step_index):        
        order = input_matrix.shape[0];
        result = np.identity(order);
        pivot = input_matrix[step_index, step_index]
        
        for line_index in range (step_index + 1, order):
            result[line_index, step_index] = (- input_matrix[line_index, step_index] / pivot)

        return result

def gauss_elimination(matrix):
    order = matrix.shape[0]
    
    for step_index in range(order-1):
        current_multiplier = get_upper_linear_combination_matrix_step(matrix, step_index)
        print(f'step {step_index}:\n{current_multiplier}')
        matrix = current_multiplier@matrix
    
    return matrix

## Gauss-jordan elimination

In [7]:
def get_lower_linear_combination_matrix_step(input_matrix, step_index):    
        order = input_matrix.shape[0];
        
        column_index = order - step_index - 1
        
        result = np.identity(order);
        pivot = input_matrix[column_index, column_index]
        
        for line_index in range (column_index - 1, -1, -1):
            result[line_index, column_index] = (- input_matrix[line_index, column_index] / pivot)
                        
        return result
    
def get_lower_decomposed_matrix(matrix):
    order = matrix.shape[0]
    
    l = np.identity(order)
    for step_index in range(order - 1):
        current_multiplier = get_lower_linear_combination_matrix_step(matrix, step_index)
        l = current_multiplier@l

    return l

def gauss_jordan_elimination(matrix):
    upper = gauss_elimination(matrix)
    lower = get_lower_decomposed_matrix(matrix)
    
    print(f'LU:\nL:\n{lower}\nU:\n{upper}')
    
    return lower@upper


In [8]:
gauss_jordan_elimination(A)

step 0:
[[ 1.  0.  0.]
 [-4.  1.  0.]
 [-4.  0.  1.]]
step 1:
[[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.  -0.5  1. ]]
LU:
L:
[[ 1.   -0.5  -0.25]
 [ 0.    1.   -0.5 ]
 [ 0.    0.    1.  ]]
U:
[[ 1.  2.  2.]
 [ 0. -4. -6.]
 [ 0.  0. -1.]]


matrix([[ 1.  ,  4.  ,  5.25],
        [ 0.  , -4.  , -5.5 ],
        [ 0.  ,  0.  , -1.  ]])