In [69]:
import numpy as np

# Gauss Elimination

## Inputs

In [70]:
A = np.matrix(
    [[5, -4, 1, 0],
    [-4, 6, -4, 1],
    [1, -4, 6, -4],
    [0, 1, -4, 5]]
)

In [71]:
B = [ -1, 2, 1, 3]

## Algorithm

In [72]:
def get_step_linear_combination_matrix(matrix_a, step_index):
    order = matrix_a.shape[0];
    result = np.identity(order);
    pivot = matrix_a[step_index, step_index]
        
    for line_index in range (step_index + 1, order):
        result[line_index, step_index] = (- matrix_a[line_index, step_index] / pivot)
    
    return result

    

In [73]:
def run_gaussian_elimination(matrix_a):
    order = matrix_a.shape[0]
    result = matrix_a
    
    for step_index in range(order-1):
        print(f'Iteration: {step_index} \n')
        current_multiplier = get_step_linear_combination_matrix(result, step_index)
        print(f'Multiplier:\n{current_multiplier}\n')
        result = current_multiplier@result
        print(f'Result:\n {result}\n')
        
    return result
    

In [74]:
run_gaussian_elimination(A)

Iteration: 0 

Multiplier:
[[ 1.   0.   0.   0. ]
 [ 0.8  1.   0.   0. ]
 [-0.2  0.   1.   0. ]
 [ 0.   0.   0.   1. ]]

Result:
 [[ 5.  -4.   1.   0. ]
 [ 0.   2.8 -3.2  1. ]
 [ 0.  -3.2  5.8 -4. ]
 [ 0.   1.  -4.   5. ]]

Iteration: 1 

Multiplier:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          1.14285714  1.          0.        ]
 [ 0.         -0.35714286  0.          1.        ]]

Result:
 [[ 5.         -4.          1.          0.        ]
 [ 0.          2.8        -3.2         1.        ]
 [ 0.          0.          2.14285714 -2.85714286]
 [ 0.          0.         -2.85714286  4.64285714]]

Iteration: 2 

Multiplier:
[[1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         1.33333333 1.        ]]

Result:
 [[ 5.         -4.          1.          0.        ]
 [ 0.          2.8        -3.2         1.        ]


matrix([[ 5.        , -4.        ,  1.        ,  0.        ],
        [ 0.        ,  2.8       , -3.2       ,  1.        ],
        [ 0.        ,  0.        ,  2.14285714, -2.85714286],
        [ 0.        ,  0.        ,  0.        ,  0.83333333]])